### ISSUE TITLE
Folders linked with datmon (also dat-desk) get transferred incorrectly

### ISSUE THREAD

**Issue by beingalink** [karissa/datmon#1]
Example:
```
<linked folder>
        |–Subfolder1
        |–Subfolder2
        |–File1
```
This becomes when fetched with dat:
```
<linked folder>  <--- empty
Subfolder1
Subfolder2
File1
```
This only happens when `datmon/dat-desk -----> dat`, `dat -----> dat`is fine.

**Comment by karissa** [comment]
Good catch. This is probably a problem in karissa/dat-manager. Will look, thank you for reporting!

**Comment by karissa** [comment]
fixed in https://github.com/karissa/dat-manager/commit/3a65c3ded35f7f0f94164a548e6067346aaf4e9e
